/*
 * OblateView.java
 */

package oblate;

import org.jdesktop.application.Action;
import org.jdesktop.application.ResourceMap;
import org.jdesktop.application.SingleFrameApplication;
import org.jdesktop.application.FrameView;
import org.jdesktop.application.TaskMonitor;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;
import javax.swing.Icon;
import javax.swing.JDialog;
import javax.swing.JFrame;

/**
 * The application's main frame.
 */
public class OblateView extends FrameView {

    public OblateView(SingleFrameApplication app) {
        super(app);

        initComponents();

        // status bar initialization - message timeout, idle icon and busy animation, etc
        ResourceMap resourceMap = getResourceMap();
        int messageTimeout = resourceMap.getInteger("StatusBar.messageTimeout");
        messageTimer = new Timer(messageTimeout, new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                statusMessageLabel.setText("");
            }
        });
        messageTimer.setRepeats(false);
        int busyAnimationRate = resourceMap.getInteger("StatusBar.busyAnimationRate");
        for (int i = 0; i < busyIcons.length; i++) {
            busyIcons[i] = resourceMap.getIcon("StatusBar.busyIcons[" + i + "]");
        }
        busyIconTimer = new Timer(busyAnimationRate, new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                busyIconIndex = (busyIconIndex + 1) % busyIcons.length;
                statusAnimationLabel.setIcon(busyIcons[busyIconIndex]);
            }
        });
        idleIcon = resourceMap.getIcon("StatusBar.idleIcon");
        statusAnimationLabel.setIcon(idleIcon);
        progressBar.setVisible(false);

        // connecting action tasks to status bar via TaskMonitor
        TaskMonitor taskMonitor = new TaskMonitor(getApplication().getContext());
        taskMonitor.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                String propertyName = evt.getPropertyName();
                if ("started".equals(propertyName)) {
                    if (!busyIconTimer.isRunning()) {
                        statusAnimationLabel.setIcon(busyIcons[0]);
                        busyIconIndex = 0;
                        busyIconTimer.start();
                    }
                    progressBar.setVisible(true);
                    progressBar.setIndeterminate(true);
                } else if ("done".equals(propertyName)) {
                    busyIconTimer.stop();
                    statusAnimationLabel.setIcon(idleIcon);
                    progressBar.setVisible(false);
                    progressBar.setValue(0);
                } else if ("message".equals(propertyName)) {
                    String text = (String)(evt.getNewValue());
                    statusMessageLabel.setText((text == null) ? "" : text);
                    messageTimer.restart();
                } else if ("progress".equals(propertyName)) {
                    int value = (Integer)(evt.getNewValue());
                    progressBar.setVisible(true);
                    progressBar.setIndeterminate(false);
                    progressBar.setValue(value);
                }
            }
        });
    }

    @Action
    public void showAboutBox() {
        if (aboutBox == null) {
            JFrame mainFrame = OblateApp.getApplication().getMainFrame();
            aboutBox = new OblateAboutBox(mainFrame);
            aboutBox.setLocationRelativeTo(mainFrame);
        }
        OblateApp.getApplication().show(aboutBox);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jLabelInitialLatitude = new javax.swing.JLabel();
        jLabelSeconds = new javax.swing.JLabel();
        jLabelDecimalDegrees = new javax.swing.JLabel();
        jLabelDegrees = new javax.swing.JLabel();
        jLabelMinutes = new javax.swing.JLabel();
        jLabelInitialLongitude = new javax.swing.JLabel();
        jLabelAzimuth = new javax.swing.JLabel();
        jLabelFeet = new javax.swing.JLabel();
        jLabelNauticalMiles = new javax.swing.JLabel();
        jLabelKilometers = new javax.swing.JLabel();
        jLabelFinalLatitude = new javax.swing.JLabel();
        jLabelFinalLongitude = new javax.swing.JLabel();
        jButtonComputeAzRange = new javax.swing.JButton();
        jButtonComputeLatLon = new javax.swing.JButton();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        jFormattedTextField3 = new javax.swing.JFormattedTextField();
        jFormattedTextField4 = new javax.swing.JFormattedTextField();
        jFormattedTextField5 = new javax.swing.JFormattedTextField();
        jFormattedTextField6 = new javax.swing.JFormattedTextField();
        jFormattedTextField7 = new javax.swing.JFormattedTextField();
        jFormattedTextField13 = new javax.swing.JFormattedTextField();
        jFormattedTextField14 = new javax.swing.JFormattedTextField();
        jFormattedTextField17 = new javax.swing.JFormattedTextField();
        jFormattedTextField18 = new javax.swing.JFormattedTextField();
        jFormattedTextField20 = new javax.swing.JFormattedTextField();
        jFormattedTextField15 = new javax.swing.JFormattedTextField();
        jFormattedTextField19 = new javax.swing.JFormattedTextField();
        jFormattedTextField21 = new javax.swing.JFormattedTextField();
        jFormattedTextField22 = new javax.swing.JFormattedTextField();
        jFormattedTextField16 = new javax.swing.JFormattedTextField();
        jFormattedTextField23 = new javax.swing.JFormattedTextField();
        jFormattedTextField24 = new javax.swing.JFormattedTextField();
        jFormattedTextField25 = new javax.swing.JFormattedTextField();
        jFormattedTextField26 = new javax.swing.JFormattedTextField();
        menuBar = new javax.swing.JMenuBar();
        javax.swing.JMenu fileMenu = new javax.swing.JMenu();
        javax.swing.JMenuItem exitMenuItem = new javax.swing.JMenuItem();
        javax.swing.JMenu helpMenu = new javax.swing.JMenu();
        javax.swing.JMenuItem aboutMenuItem = new javax.swing.JMenuItem();
        statusPanel = new javax.swing.JPanel();
        javax.swing.JSeparator statusPanelSeparator = new javax.swing.JSeparator();
        statusMessageLabel = new javax.swing.JLabel();
        statusAnimationLabel = new javax.swing.JLabel();
        progressBar = new javax.swing.JProgressBar();

        mainPanel.setMaximumSize(new java.awt.Dimension(680, 325));
        mainPanel.setMinimumSize(new java.awt.Dimension(680, 325));
        mainPanel.setOpaque(false);
        mainPanel.setPreferredSize(new java.awt.Dimension(680, 325));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(oblate.OblateApp.class).getContext().getResourceMap(OblateView.class);
        jLabelInitialLatitude.setText(resourceMap.getString("jLabelInitialLatitude.text")); // NOI18N
        mainPanel.add(jLabelInitialLatitude, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabelSeconds.setText(resourceMap.getString("jLabelSeconds.text")); // NOI18N
        mainPanel.add(jLabelSeconds, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, -1, -1));

        jLabelDecimalDegrees.setText(resourceMap.getString("jLabelDecimalDegrees.text")); // NOI18N
        mainPanel.add(jLabelDecimalDegrees, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, -1));

        jLabelDegrees.setText(resourceMap.getString("jLabelDegrees.text")); // NOI18N
        mainPanel.add(jLabelDegrees, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, -1, -1));

        jLabelMinutes.setText(resourceMap.getString("jLabelMinutes.text")); // NOI18N
        mainPanel.add(jLabelMinutes, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, -1, -1));

        jLabelInitialLongitude.setText(resourceMap.getString("jLabelInitialLongitude.text")); // NOI18N
        mainPanel.add(jLabelInitialLongitude, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabelAzimuth.setText(resourceMap.getString("jLabelAzimuth.text")); // NOI18N
        mainPanel.add(jLabelAzimuth, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabelFeet.setText(resourceMap.getString("jLabelFeet.text")); // NOI18N
        mainPanel.add(jLabelFeet, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, -1, -1));

        jLabelNauticalMiles.setText(resourceMap.getString("jLabelNauticalMiles.text")); // NOI18N
        mainPanel.add(jLabelNauticalMiles, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, -1, -1));

        jLabelKilometers.setText(resourceMap.getString("jLabelKilometers.text")); // NOI18N
        mainPanel.add(jLabelKilometers, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        jLabelFinalLatitude.setText(resourceMap.getString("jLabelFinalLatitude.text")); // NOI18N
        mainPanel.add(jLabelFinalLatitude, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jLabelFinalLongitude.setText(resourceMap.getString("jLabelFinalLongitude.text")); // NOI18N
        mainPanel.add(jLabelFinalLongitude, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        jButtonComputeAzRange.setText(resourceMap.getString("jButtonComputeAzRange.text")); // NOI18N
        mainPanel.add(jButtonComputeAzRange, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 260, -1, 50));

        jButtonComputeLatLon.setText(resourceMap.getString("jButtonComputeLatLon.text")); // NOI18N
        mainPanel.add(jButtonComputeLatLon, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, 50));

        jFormattedTextField2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.############"))));
        mainPanel.add(jFormattedTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 160, -1));

        jFormattedTextField3.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.############"))));
        mainPanel.add(jFormattedTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 160, -1));

        jFormattedTextField4.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        mainPanel.add(jFormattedTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 160, -1));

        jFormattedTextField5.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.####"))));
        mainPanel.add(jFormattedTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 160, -1));

        jFormattedTextField6.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.############"))));
        mainPanel.add(jFormattedTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 160, -1));

        jFormattedTextField7.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.############"))));
        mainPanel.add(jFormattedTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 160, -1));

        jFormattedTextField13.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.####"))));
        mainPanel.add(jFormattedTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, 260, -1));

        jFormattedTextField14.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        mainPanel.add(jFormattedTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 90, -1));

        jFormattedTextField17.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.######"))));
        mainPanel.add(jFormattedTextField17, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, 90, -1));

        jFormattedTextField18.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.######"))));
        mainPanel.add(jFormattedTextField18, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 30, 140, -1));

        jFormattedTextField20.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.####"))));
        mainPanel.add(jFormattedTextField20, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, 260, -1));

        jFormattedTextField15.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        mainPanel.add(jFormattedTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, 90, -1));

        jFormattedTextField19.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.######"))));
        mainPanel.add(jFormattedTextField19, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, 90, -1));

        jFormattedTextField21.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.######"))));
        mainPanel.add(jFormattedTextField21, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 60, 140, -1));

        jFormattedTextField22.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.######"))));
        mainPanel.add(jFormattedTextField22, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 220, 90, -1));

        jFormattedTextField16.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        mainPanel.add(jFormattedTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, 90, -1));

        jFormattedTextField23.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.######"))));
        mainPanel.add(jFormattedTextField23, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 220, 140, -1));

        jFormattedTextField24.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        mainPanel.add(jFormattedTextField24, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, 90, -1));

        jFormattedTextField25.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.######"))));
        mainPanel.add(jFormattedTextField25, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 190, 90, -1));

        jFormattedTextField26.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.######"))));
        mainPanel.add(jFormattedTextField26, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 190, 140, -1));

        fileMenu.setText(resourceMap.getString("fileMenu.text")); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(oblate.OblateApp.class).getContext().getActionMap(OblateView.class, this);
        exitMenuItem.setAction(actionMap.get("quit")); // NOI18N
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        helpMenu.setText(resourceMap.getString("helpMenu.text")); // NOI18N

        aboutMenuItem.setAction(actionMap.get("showAboutBox")); // NOI18N
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        statusAnimationLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout statusPanelLayout = new javax.swing.GroupLayout(statusPanel);
        statusPanel.setLayout(statusPanelLayout);
        statusPanelLayout.setHorizontalGroup(
            statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(statusPanelSeparator, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)
            .addGroup(statusPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(statusMessageLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 494, Short.MAX_VALUE)
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusAnimationLabel)
                .addContainerGap())
        );
        statusPanelLayout.setVerticalGroup(
            statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusPanelLayout.createSequentialGroup()
                .addComponent(statusPanelSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusMessageLabel)
                    .addComponent(statusAnimationLabel)
                    .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3))
        );

        setComponent(mainPanel);
        setMenuBar(menuBar);
        setStatusBar(statusPanel);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonComputeAzRange;
    private javax.swing.JButton jButtonComputeLatLon;
    private javax.swing.JFormattedTextField jFormattedTextField13;
    private javax.swing.JFormattedTextField jFormattedTextField14;
    private javax.swing.JFormattedTextField jFormattedTextField15;
    private javax.swing.JFormattedTextField jFormattedTextField16;
    private javax.swing.JFormattedTextField jFormattedTextField17;
    private javax.swing.JFormattedTextField jFormattedTextField18;
    private javax.swing.JFormattedTextField jFormattedTextField19;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JFormattedTextField jFormattedTextField20;
    private javax.swing.JFormattedTextField jFormattedTextField21;
    private javax.swing.JFormattedTextField jFormattedTextField22;
    private javax.swing.JFormattedTextField jFormattedTextField23;
    private javax.swing.JFormattedTextField jFormattedTextField24;
    private javax.swing.JFormattedTextField jFormattedTextField25;
    private javax.swing.JFormattedTextField jFormattedTextField26;
    private javax.swing.JFormattedTextField jFormattedTextField3;
    private javax.swing.JFormattedTextField jFormattedTextField4;
    private javax.swing.JFormattedTextField jFormattedTextField5;
    private javax.swing.JFormattedTextField jFormattedTextField6;
    private javax.swing.JFormattedTextField jFormattedTextField7;
    private javax.swing.JLabel jLabelAzimuth;
    private javax.swing.JLabel jLabelDecimalDegrees;
    private javax.swing.JLabel jLabelDegrees;
    private javax.swing.JLabel jLabelFeet;
    private javax.swing.JLabel jLabelFinalLatitude;
    private javax.swing.JLabel jLabelFinalLongitude;
    private javax.swing.JLabel jLabelInitialLatitude;
    private javax.swing.JLabel jLabelInitialLongitude;
    private javax.swing.JLabel jLabelKilometers;
    private javax.swing.JLabel jLabelMinutes;
    private javax.swing.JLabel jLabelNauticalMiles;
    private javax.swing.JLabel jLabelSeconds;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JLabel statusAnimationLabel;
    private javax.swing.JLabel statusMessageLabel;
    private javax.swing.JPanel statusPanel;
    // End of variables declaration//GEN-END:variables

    private final Timer messageTimer;
    private final Timer busyIconTimer;
    private final Icon idleIcon;
    private final Icon[] busyIcons = new Icon[15];
    private int busyIconIndex = 0;

    private JDialog aboutBox;
}
